=== louisharris/dissertation-text-summarisation/duc2001_simplified/training/unified.dtd
<!ELEMENT CORPUS (SUM*, DOC*)>

<!ELEMENT  SUM   (#PCDATA|S)*> 
<!ATTLIST  SUM     
                  DOCREF     CDATA                    #REQUIRED
                  SELECTOR   CDATA                    #REQUIRED
                  SIZE       (50|100|200|400)         #REQUIRED
                  SUMMARIZER (A|B|C|D|E|F|G|H|I|J|K)  #REQUIRED
                  TYPE       (MULTI|PERDOC)           #REQUIRED> 
<!--
   SJMN San Jose Mercury and News
   WSJ  Wall Street Journal
   LA   Los Angeles Times
   AP   Associated Press
   FBIS Foreign Broadcast Information Service
   FT   Financial Times, London
-->

<!ELEMENT DOC (#PCDATA|DOCNO|SOURCE|KEYWORDS|DATE|DATELINE|DATELINE_STATE|DATELINE_REGION|DATELINE_CITY|DATELINE_COUNTRY|HEADLINE|TEXT|ORIG_SOURCE|ABS)*>

<!ATTLIST DOC
     SCORE CDATA #IMPLIED
     RANK  CDATA #IMPLIED
     QID   CDATA #IMPLIED
>

<!ELEMENT DOCNO (#PCDATA)>
<!ELEMENT SOURCE (#PCDATA)>
<!ELEMENT ORIG_SOURCE (#PCDATA)>
<!ELEMENT HEADLINE (HL)+>
<!ELEMENT KEYWORDS (#PCDATA)>
<!ELEMENT HL (#PCDATA)>
<!ELEMENT DATE (DAY, MONTH, YEAR)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT MONTH (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT P (#PCDATA|SUB_HEAD|STAGE_DIR|BREAK|BULLET|GRAPIC)*>
<!ELEMENT TEXT (#PCDATA|P|STAGE_DIR|BULLET|GRAPHIC|TRAILER|SUB_HEAD)*>
<!ELEMENT DATELINE (#PCDATA)>
<!ELEMENT DATELINE_CITY (#PCDATA)>
<!ELEMENT DATELINE_REGION (#PCDATA)>
<!ELEMENT DATELINE_COUNTRY (#PCDATA)>
<!ELEMENT DATELINE_STATE (#PCDATA)>
<!ELEMENT ABS (#PCDATA)>

<!-- BARRY -->

<!ELEMENT TRAILER (#PCDATA|P)*>
<!ELEMENT BREAK (#PCDATA|P)*>
<!ELEMENT BULLET (#PCDATA)>
<!ELEMENT SUB_HEAD (#PCDATA|STAGE_DIR)*>
<!ELEMENT GRAPHIC (#PCDATA|SUB_HEAD|P)*>
<!ELEMENT STAGE_DIR (#PCDATA)>

<!ELEMENT S (#PCDATA)*>

=== louisharris/dissertation-text-summarisation/duc2001_simplified/testing/d21d.xml
<?xml version='1.0'?>
<!DOCTYPE CORPUS SYSTEM "unified.dtd" >
<CORPUS>
<DOC>
<DOCNO>AP880316-0061
</DOCNO>
<SOURCE> AP 
</SOURCE>
<DATE> 
<DAY>16
</DAY> 
<MONTH>03
</MONTH> 
<YEAR>88
</YEAR> 
</DATE>
<HEADLINE>
<HL>
Fire Breaks Out On Cruise Ship With 700 Aboard
</HL>
</HEADLINE>
<DATELINE>MIAMI (AP) 
</DATELINE>
<TEXT>
<P>
An engine fire broke out early today on a cruise
ship carrying more than 700 people in the Gulf of Mexico, but the
blaze appeared to have been brought under control, according to
officials and a nearby ship's captain.
</P>
<P>
No injuries were reported, said Petty Officer Brian Lincoln, of
the U.S. Coast Guard's Miami office.
</P>
<P>
The Scandinavian Star was about 35 miles off Isla Mujeres, a
Mexican island north of the tourist resort Cancun in the Yucatan
peninsula, said Coast Guard Lt. Jim Mazzonna in Miami.
``All we know is that the ship's captain ... is completely out
of fire-fighting equipment and has requested additional
fire-fighting equipment such as foam, water and CO2,'' said
Lincoln, referring to carbon dioxide.
</P>
<P>
Coast Guard cutters, the Canada Star cruise ship and the vessel
Vera Cruz stood by to assist in evacuating passengers, Lincoln said.
</P>
<P>
The Canada Star's captain, Jens Thorn, said later that the fire
appeared to have been brought under control, and there was no
reason to evacuate.
</P>
<P>
Coast Guard Petty Officer Richard Esterline said 707 people,
including crew, were aboard the ship.
</P>
<P>
The Scandinavian Star, owned by SeaEscape Ltd., offers daily
``cruises to nowhere'' out of its port in St. Petersburg, records
show.
</P>
</TEXT>
</DOC>
<DOC>
<DOCNO>AP880316-0208
</DOCNO>
<SOURCE> AP 
</SOURCE>
<DATE> 
<DAY>16
</DAY> 
<MONTH>03
</MONTH> 
<YEAR>88
</YEAR> 
</DATE>
<HEADLINE>
<HL>
Fire Disables Cruise Ship in Gulf of Mexico
</HL>
</HEADLINE>
<DATELINE>MIAMI (AP) 
</DATELINE>
<TEXT>
<P>
An engine room fire Wednesday disabled a cruise
ship off the Mexican coast, but the crew extinguished the blaze and
the ship with 715 people aboard was towed to port.
</P>
<P>
The Navy cutter Vigilant escorted the 465-foot ship, the
Scandinavian Star, as a precaution, according to Chief Petty
Officer Luis Diaz of the U.S. Coast Guard in Miami.
``The fire is out and the ship is being towed by the Mexican
navy to Cancun,'' said Diaz.
</P>
<P>
There were no injuries from the fire, but a 71-year-old St.
</P>
<P>
Petersburg man who suffered a heart attack was in stable condition
and on his way home aboard a Coast Guard plane.
</P>
<P>
A second person who suffered a spinal cord injury was also
evacuated with the heart attack victim, but Diaz said that injury
also was apparently not related to the fire.
</P>
<P>
The ship was expected to arrive in Cancun late Wednesday or
Thursday. The 449 passengers will be flown to St. Petersburg, said
Jill DeChello, spokesman for the ship's owner, SeaEscape Ltd. of
Miami.
</P>
<P>
The Scandinavian Star was on a 3-day cruise to Cozumel, Mexico,
and was returning to St. Petersburg when the fire broke out about 1
a.m. EST Wednesday, she said.
</P>
<P>
The crew sealed off the engine room and pumped in carbon dioxide
to put out the fire.
``They used all their CO2 and closed off the engine room,'' said
Diaz. ``Then they requested more assistance from the Coast Guard.''
The fire was already extinguished when the Vigilant arrived about
10 a.m., he added.
</P>
<P>
Ms. DeChello said the company did not know what sparked the fire.
``It will take a week before we know the cause and the extent of
the damage,'' said Ms. DeChello.
</P>
<P>
In August 1984, a fire struck the Star's sister ship, the
Scandinavian Sun, in the port of Miami, killing a passenger and a
crewman.
``I feel they are two totally different incidents that are in no
way related,'' said Ms. DeChello. She said the cruise line was
inspected by the Coast Guard and rigorously enforced all safety
rules.
</P>
<P>
Wednesday's fire occurred as the Scandinavian Star was about 35
miles off Isla Mujeres, a Mexican island north of the tourist
resort Cancun in the Yucatan peninsula, the Coast Guard said.
</P>
</TEXT>
</DOC>
<DOC>
<DOCNO>AP880622-0262
</DOCNO>
<SOURCE> AP 
</SOURCE>
<DATE> 
<DAY>22
</DAY> 
<MONTH>06
</MONTH> 
<YEAR>88
</YEAR> 
</DATE>
<HEADLINE>
<HL>
NTSB Says Cruise Industry Safety May Be Below Par
</HL>
</HEADLINE>
<DATELINE>MIAMI (AP) 
</DATELINE>
<TEXT>
<P>
Safety standards may not be stringent enough in the
cruise industry, the chairman of a federal agency investigating the
March engine-room fire aboard the Scandinavian Star said Wednesday.
``The cruise ship industry is generally not operated under the
U.S. flag. You do have visits by the Coast Guard, but those are
paper certifications,'' said Jim Burnett, chairman of the National
Transportation Safety Board.
``There may not be sufficient safety standards,'' he said,
adding that his agency has probed fires aboard four cruise ships in
the past five years. ``The potential for loss of life is enormous.''
The March 15 engine-room fire aboard the Star, carrying 439
mostly American passengers, was discovered by a crew member as the
ship returned from Cozumel, Mexico to its Tampa home port.
</P>
<P>
Smoke detectors apparently failed, as did an automatic system to
douse flames. Also, the ship's emergency generators didn't work for
an hour, leaving the vessel without power in rough seas in the
Yucatan Channel, according to NTSB reports released as the agency's
three-day hearing opened here.
``Although there were no injuries or deaths, the failure of the
vessel's safety systems highlights the potential for a catastrophic
loss of life in this accident and future vessel fires,'' Burnett
said.
</P>
<P>
The safety board will examine whether the existing Coast Guard
procedures and international regulations are adequate to protect
passengers or whether more rigorous standards are needed.
</P>
<P>
Because the NTSB lacks regulatory authority and because cruise
ships are often registered outside the United States, he said his
agency can only make recommendations. These might have to be
followed up with congressional action or with new treaties with
nations where ships are registered, Burnett said.
</P>
<P>
The 465-foot Star, operated by Miami-based SeaEscape Limited, is
registered in the Bahamas. Its engine room was badly damaged by the
fire, and there was smoke and water damage throughout the
17-year-old French-made ship, which has since been repaired.
</P>
<P>
Burnett estimated damages at about $20 million, but SeaEscape
officials did not answer questions at the hearing.
</P>
<P>
SeaEscape lawyer Nils Linfors Jr. vowed to challenge in court
the NTSB's authority to hold such public hearings as Wednesday's.
</P>
<P>
Atissue is that the board does not permit cross-examinations and
contentions that the Bahamian-registered ship is outside the
agency's jurisdiction.
</P>
<P>
An NTSB report said the fire ignited when pressurized fuel
leaked from a line and sprayed against a hot engine exhaust
manifold. The leak continued for 13 minutes after the fire was
discovered, feeding the flames, the report said.
</P>
<P>
Because smoke detectors apparently weren't working, Capt. Peter
Schaab said he had to send an officer to the engine room to confirm
there was a fire.
</P>
<P>
Firefighting efforts were hampered when an automatic carbox
dioxide extinguishing system failed, and had to be operated by
hand. But the fire was contained to the engine room.
``There was no further spreading,'' said Schaab, who was praised
by Burnett for his 268-member crew acting quickly to move
passengers from ship discos, bars, shows and dining rooms. There
were no serious injuries to passengers or crew.
</P>
<P>
NTSB records show that between September 1987 and February 1988,
there were at least six leaks in fuel pipes that feed the engines.
</P>
<P>
The official analysis of the fire and any recommendations that
come out of the hearings will be adopted by the full NTSB board in
Washington later this summer.
</P>
</TEXT>
</DOC>
<DOC>
<DOCNO>AP881017-0098
</DOCNO>
<SOURCE> AP 
</SOURCE>
<DATE> 
<DAY>17
</DAY> 
<MONTH>10
</MONTH> 
<YEAR>88
</YEAR> 
</DATE>
<HEADLINE>
<HL>
Soviet Passenger Ship Catches Fire; All Aboard Reported Safe
</HL>
</HEADLINE>
<DATELINE>MOSCOW (AP) 
</DATELINE>
<TEXT>
<P>
Fire broke out aboard a Soviet passenger liner
carrying French tourists on a cruise of the Mediterranean, but the
blaze was put out by the crew and no passengers were injured, Tass
reported Monday.
</P>
<P>
The Shota Rustaveli was 25 miles off the island of Malta when a
blaze broke out in the auxiliary engine room, the official news
agency said.
``The blaze was put out by the crew. There are no casualties
among the passengers,'' Tass said.
</P>
<P>
It cited local news reports as saying the ship had docked at the
Maltese port of Valletta, and that its passengers had been offered
sightseeing trips around the island south of Sicily.
</P>
<P>
The tourists were expected to continue their voyage on another
Soviet ship, and the crew of the Shota Rustaveli was to make
repairs and bring the ship home, Tass said.
</P>
<P>
It was the second fire aboard a Soviet cruise ship in recent
months. On May 18, a blaze broke out on the liner Priamurye while
it was in the Japanese port of Osaka. Eleven Soviets were killed in
the Priamurye fire, and 26 others hospitalized in critical
condition, Tass reported. The ship was carrying 295 Soviets on a
youth cruise around Japan.
</P>
</TEXT>
</DOC>
<DOC>
<DOCNO>AP881109-0149
</DOCNO>
<SOURCE> AP 
</SOURCE>
<DATE> 
<DAY>09
</DAY> 
<MONTH>11
</MONTH> 
<YEAR>88
</YEAR> 
</DATE>
<HEADLINE>
<HL>
Small Fire Interupts Cruise, No Injuries
</HL>
</HEADLINE>
<DATELINE>MIAMI (AP) 
</DATELINE>
<TEXT>
<P>
The cruise ship Song of America was forced to return
to port after an engine seized up and started a small fire, but no
one was hurt, the ship's owner said today.
</P>
<P>
The ship left Miami on Sunday with about 1,300 passengers on a
Caribbean cruise.
</P>
<P>
